export const CHANGE_WEATHER_POSITION = "CHANGE_WEATHER_POSITION";
export const SET_WEATHER = "SET_WEATHER";
export const CHANGE_MAP_CENTER = "CHANGE_MAP_CENTER";
export const SET_CURRENT_MARKER = "SET_CURRENT_MARKER";
export const GET_MARKERS = "GET_MARKERS";
export const LIKE_STORE = "LIKE_STORE";
export const SET_CURRENT_LIKE = "SET_CURRENT_LIKE";